name: flutter_dio_retrofit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # other
  logger: ^2.2.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0

  # State
  flutter_riverpod: ^2.5.1

  # REST API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true